### ISSUE TITLE
Not able to execute chap9 on ubuntu server edition 

### ISSUE THREAD

**Issue by Niteshsuresh** [pratian-pyclub/pocs#1]
drawing grammar
(S[-INV]
  (Adv[+NEG] rarely)
  (S[+INV]
    (V[+AUX] do)
    (NP[-WH] you)
    (VP[] (V[-AUX, SUBCAT='intrans'] sing))))
Traceback (most recent call last):
  File "chap9.py", line 126, in <module>
    main()
  File "chap9.py", line 122, in main
    sentence_parsing()
  File "chap9.py", line 113, in sentence_parsing
    tree.draw()
  File "/home/nitesh/.local/lib/python2.7/site-packages/nltk/tree.py", line 686, in draw
    draw_trees(self)
  File "/home/nitesh/.local/lib/python2.7/site-packages/nltk/draw/tree.py", line 866, in draw_trees
    TreeView(*trees).mainloop()
  File "/home/nitesh/.local/lib/python2.7/site-packages/nltk/draw/tree.py", line 759, in __init__
    self._top = Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by swaathi** [comment]
Weird. Does this work for you? https://github.com/pratian-pyclub/nlp-pocs/blob/master/chap7/simple_noun_phrase_chunking.py#L15

There's an issue with drawing the tree. I think some package is missing!

**Comment by Niteshsuresh** [comment]
@swaathi . Yes not able to execute that as well

**Comment by swaathi** [comment]
Then some dependency is missing in your end. Check if matplotlib is installed?

**Comment by Niteshsuresh** [comment]
Got it installed. Still the same issue. Is something to with GUI issue?. I'm using putty to connect to server.

**Comment by swaathi** [comment]
Maybe yes. Since the graph opens a new window.

Either way, it’s not overly important. Just a nice visualization. If you see just above the dump, there’s a graph like structure drawn in text. That should be sufficient.

**Comment by Niteshsuresh** [comment]
I have code commented draw() method. Thx
